name: labaaa1
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest    
    steps:
      - name: Yandex Image Registry Action
        uses: pyropy/yandex-cloud-image-registry@v0.8-alpha
        with:
          YC_SERVICE_ACCOUNT_KEY_FILE: ${{secrets.JSON_KEY}}
          YC_IMG_REGISTRY_ID: crpsc3d0o4hdv80ri13f
          DOCKER_IMG_NAME: labaaa1
      - run: echo docker build -t \cr.yandex/crpsc3d0o4hdv80ri13f/labaaa1:igg
      - run: echo docker push \cr.yandex/crpsc3d0o4hdv80ri13f/labaaa1:igg
  
