name: labaaa1
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: json yc iam key create —service-account-name github0actions -o key.json
      - run: echo docker build -t \cr.yandex/crpsc3d0o4hdv80ri13f/labaaa1:igg
      - run: echo docker push \cr.yandex/crpsc3d0o4hdv80ri13f/labaaa1:igg
 
